// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Feed struct {
	ID            uuid.UUID
	Name          string
	Url           string
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	UserID        uuid.UUID
	LastFetchedAt sql.NullTime
}

type FeedFollow struct {
	ID        uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	FeedID    uuid.UUID
	UserID    uuid.UUID
}

type Post struct {
	ID          uuid.UUID
	Title       string
	Description string
	Url         string
	Published   time.Time
	FeedID      uuid.NullUUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Username  string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	ApiKey    string
}
